permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
  keepalive: 60
  password: zigbee2mqttpasswd
  reject_unauthorized: true
  user: zigbee2mqtt
  version: 4
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8080
homeassistant: true
